# Generated by Django 3.1.2 on 2021-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='task_pic',
            field=models.FileField(upload_to='images'),
        ),
    ]
