# Generated by Django 3.1.2 on 2021-06-02 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0005_auto_20210602_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
