# Generated by Django 3.1.2 on 2021-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_auto_20210602_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='task_pic',
            field=models.ImageField(blank=True, upload_to='task_app/images'),
        ),
    ]
