# Generated by Django 3.1.2 on 2021-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_auto_20210602_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskupload',
            options={'ordering': ['-create_time_stamp']},
        ),
        migrations.AlterField(
            model_name='taskupload',
            name='create_time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
