# Generated by Django 3.1.2 on 2021-06-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_auto_20210602_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskupload',
            options={'ordering': ['-create_timestamp']},
        ),
        migrations.RenameField(
            model_name='taskupload',
            old_name='create_time_stamp',
            new_name='create_timestamp',
        ),
    ]
