# Generated by Django 3.1.2 on 2021-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_auto_20210602_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='task_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
