# Generated by Django 3.1.2 on 2021-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0013_auto_20210602_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heirarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('title', models.TextField(max_length=40)),
                ('parentId', models.IntegerField(null=True)),
            ],
        ),
    ]
