# Generated by Django 3.1.2 on 2021-06-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_heirarchy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heirarchy',
        ),
    ]
