# Generated by Django 3.1.2 on 2021-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heirarchy',
            name='parentId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
